model:
  arch: genechat
  model_type: pretrain_vicuna

  adaptor_type: "mlp"

  freeze_gene_encoder: True
  freeze_adaptor: True
  freeze_llama: False

  max_gene_length: 5000

  gene_model: "hyenadna-medium-160k-seqlen"
  llama_model: "/home/namdo/applications/GeneChat/llama_pretrained/vicuna-13b-v1.5"

  prompt: ""

  max_txt_len: 512
  end_sym: "</s>"
  low_resource: False
  embedding_agg: 1
  peft_ckpt: '/data2/namdo/checkpoint_cot/20260427072/checkpoint_50000.pth'
  stage1_ckpt: ''

datasets:
  seq_mrna:
    data_type: gene
    build_info:
      train:
        storage: /home/namdo/applications/data_hm/train_hm

run:
  task: protein_text_pretrain
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False
  printable: True
